// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABwyQER7RLaPpPz6bwDxSjeUyVqyGsAzQ',
    appId: '1:800995131542:android:1febbe0f0680dcf8fe82b7',
    messagingSenderId: '800995131542',
    projectId: 'tiktok-clone-ef77d',
    storageBucket: 'tiktok-clone-ef77d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlkTD2BJ3ZAU4xjlBofwMK6g2UrBLregA',
    appId: '1:800995131542:ios:ee19a3931123f52afe82b7',
    messagingSenderId: '800995131542',
    projectId: 'tiktok-clone-ef77d',
    storageBucket: 'tiktok-clone-ef77d.appspot.com',
    androidClientId:
        '800995131542-mnnjenabllep88dd39pb57q5gab42usv.apps.googleusercontent.com',
    iosClientId:
        '800995131542-663fajqsucsqqo0l204397qvqvs9n2up.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
