name: Build Release App Bundle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_KEYSTORE_PATH: ${{ secrets.KEYSTORE }}
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      # - name: move to android folder
      #     id: build
      #     run: bash ./gradlew assembleRelease
      - name: Build APK
          id: build
          run: bash ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.3.10"
      - name: Pub Get Packages
        run: flutter pub get
      - name: Build apk release
        run: flutter build apk --release
      - name: upload apk to App Center
        uses: wzieba/AppCenter-Github-Action@v1
      
        with:
          appName: tiktok_clone_android
          token: 53540ce96a4fad0d4511636629a99d76e557ec4f
          group: public
          file: build/app/outputs/flutter-apk/app-release.apk
          notifyTesters: true
          debug: false