name: deploy-android-appcenter
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build release
        run: ./gradlew assembleRelease
      - name: upload apk to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: tiktok_clone_android
          token: 53540ce96a4fad0d4511636629a99d76e557ec4f
          group: public
          file: build/app/outputs/flutter-apk/app-release.apk
          notifyTesters: true
          debug: false
          